spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kotlin_db?useSSL=false
    username: user
    password: password
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    database: mysql
    show-sql: true